### ISSUE TITLE
Publish assertlog into maven central

### ISSUE THREAD

**Issue by nick318** [codeborne/assertlog#1]
Can you publish assertlog into maven central?

**Comment by asolntsev** [comment]
Sure. I can do it asap. I just thought it is not mature enough, but who cares..

**Comment by asolntsev** [comment]
@nick318 Done. Currently only JUnit4 and Log4j are supported. 

You need to add this dependency to your project:

```groovy
testImplementation('com.codeborne.assertlog:assertlog-log4j-junit4:0.1')
```
